### ISSUE TITLE
DbUpdateConcurrencyException when deleting expired session from store

### ISSUE THREAD

**Issue by johnTaylorAtPropertyMe** [DuendeSoftware/BFF#63]
**Which version of Duende IdentityServer are you using?**
* Duende.BFF 1.1.0-preview.1
* Duende.BFF.EntityFramework 1.1.0-preview.1
* Duende.BFF.Yarp 1.1.0-preview.1

**Which version of .NET are you using?**
.NET 6.0

**Describe the bug**
Concurrent/parallel requests with a cookie associated with an expired authentication ticket will result in one request removing the expired session from the store and the other throwing a `DbUpdateConcurrencyException`. This generates a server error rather than `401 Unauthorized` for the caller.

**To Reproduce**
The same behaviour can be reproduced in a contrived test harness that:
* Creates a session in the database
* Makes parallel calls to `DeleteUserSessionAsync` via separate DI scopes

Repro in test [here](https://github.com/johnTaylorAtPropertyMe/BFF/commit/43ad6a1f3f5f3971fcbd83af168261d1c6ef54cb).

**Expected behaviour**
No exception thrown

**Log output/exception with stacktrace**

```
Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException: The database operation was expected to affect 1 row(s), but actually affected 0 row(s); data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ThrowAggregateUpdateConcurrencyException(Int32 commandIndex, Int32 expectedRowsAffected, Int32 rowsAffected)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeResultSetWithoutPropagationAsync(Int32 commandIndex, RelationalDataReader reader, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeAsync(RelationalDataReader reader, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Pomelo.EntityFrameworkCore.MySql.Storage.Internal.MySqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Duende.Bff.EntityFramework.UserSessionStore.DeleteUserSessionAsync(String key, CancellationToken cancellationToken) in /_/src/Duende.Bff.EntityFramework/UserSessionStore.cs:line 65
   at Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler.ReadCookieTicket()
   at Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler.HandleAuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Additional context**
We see the exceptions regularly, but at low rates (circa 1% of total traffic) in a real world environment

**Comment by brockallen** [comment]
This is a larger issue than just delete, I think. It could happen with two requests updating the same session as well (due to renewal of the refresh token or just sliding the session).

Do you have a suggestion on what we might do here? One idea would be to catch that exception and ignore it based on the assumption that it's just recently been updated (or deleted) and the other update/delete is "good enough", so the second can be ignored.

Thoughts?

**Comment by johnTaylorAtPropertyMe** [comment]
It could well be a larger issue, though fortunately I don't think it's likely with the current implementation.

The EF type configuration for `UserSession` doesn't have a property configured with `IsRowVersion` or `IsConcurrencyToken` so updates will be written to the table without throwing the exception. This may well be "good enough" if the intent of the update is the same.

With respect to the delete scenario, it might be an idea to catch the exception and ignore on the proviso that the record has already been deleted or otherwise re-throw the original exception:

```
public async Task DeleteUserSessionAsync(string key, CancellationToken cancellationToken)
{
    // ... snipped for brevity ... 
    _sessionDbContext.UserSessions.Remove(item);

    try
    {
        await _sessionDbContext.SaveChangesAsync(cancellationToken);
    }
    catch (DbUpdateConcurrencyException ex)
    {                    
        _logger.LogWarning(ex, "Caught exception when trying to delete user session for key {key}", key);

        foreach (var entry in ex.Entries)
        {
            if (await entry.GetDatabaseValuesAsync(cancellationToken) != null) throw;
        }
    }
    
    // ... snipped for brevity ... 
}
```

This is probably overkill - If the scenario is only going to occur on a deleted row, it's likely safe to ignore the exception and skip an extra call to the DB.

If a combination of delete/update (due to a sliding session) were to happen concurrently, you'd probably argue that it's exceptional and can throw unless a requirement were to arise to warrant further treatment.

**Comment by ylr-research** [comment]
In my experience I've seen ConcurrncyToken for updates. For delete I think using `lock` will do the trick

**Comment by brockallen** [comment]
Ok, I didn't think about the updates not having the concurrency columns, so those are already working as I said above (meaning, multiple updates at the same time are all likely good enough).

So then the only pending issue is the delete -- yes, I think catching the exception will suffice. I'll get to work on that.

Thanks for letting us know about this.

**Comment by brockallen** [comment]
> In my experience I've seen Concurrency Token for updates. For delete I think using lock will do the trick.

Not if this happens concurrently from multiple servers, which I believe could happen.

**Comment by ylr-research** [comment]
So the test scenario exposed above was for 2 threads (2 CPU) in the same server, right?

**Comment by brockallen** [comment]
> So the test scenario exposed above was for 2 threads (2 CPU) in the same server, right?

I'm not sure what you mean. The OP said that if 2 concurrent requests are trying to delete the same record, then it's possible that from the time it's loaded into an entity then the DbCtx tries to delete it from the DB it's already been deleted. That's possible across multiple servers, so the in-memory lock wouldn't not suffice.

**Comment by brockallen** [comment]
@johnTaylorAtPropertyMe I submitted a PR. Please have a look and let us know what you think. Thanks.

**Comment by ylr-research** [comment]
I see @brockallen. You're right about that. Lock won't work for distributed systems. Then, the easiest solution is indeed catch and ignore.

**Comment by johnTaylorAtPropertyMe** [comment]
@brockallen: Looks like it'll do the trick!

I pulled the branch and ran my original test (with an extra `SaveChanges` call on each context) against a real database to rule out any semantic differences with the in-memory provider.... No issues to report!

**Comment by brockallen** [comment]
Ok, thanks. We'll merge it in next week and get a release out. Happy new year!
