### ISSUE TITLE
BFFMiddleWare calls Add on HttpContext.Items rather than TryAdd causing error

### ISSUE THREAD

**Issue by jimitndiaye** [DuendeSoftware/BFF#75]
**Which version of Duende IdentityServer are you using?**
Version 1.1.3 of Duende.BFF and Duende.BFF.Yarp
**Which version of .NET are you using?**
.Net 6
**Describe the bug**
BFFMiddleware does not check to see if it has already been registered and calls ```Add``` on the Items dictionary which throws an error:

Should use ```context.Items.TryAdd``` rather than ```context.Items.Add``` or simply set it via the index.

**To Reproduce**

Call ```app.UseBff``` more than once at startup.

**Expected behavior**
The BFFMiddleware should only be registered once and should check if it has already been registered.

**Log output/exception with stacktrace**

```
System.ArgumentException: An item with the same key has already been added. Key: Duende.Bff.BffMiddlewareMarker
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Microsoft.AspNetCore.Http.ItemsDictionary.System.Collections.Generic.IDictionary<System.Object,System.Object>.Add(Object key, Object value)
   at Duende.Bff.Endpoints.BffMiddleware.Invoke(HttpContext context) in /_/src/Duende.Bff/BffMiddleware.cs:line 43
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at OrchardCore.Diagnostics.DiagnosticsStartupFilter.<>c__DisplayClass3_0.<<Configure>b__1>d.MoveNext()
`
```

**Additional context**
Application startup may be reentrant or UseBff may be called multiple times by mistake but it shouldn't crash the app. Even the AuthorizationMiddleware uses something similar:
```c#
                context.Items[AuthorizationMiddlewareInvokedWithEndpointKey] = AuthorizationMiddlewareWithEndpointInvokedValue;
```

**Comment by leastprivilege** [comment]
Thanks! PR created.
